### ISSUE TITLE
onnx conversion

### ISSUE THREAD

**Issue by harishprabhala** [kamalkraj/stable-diffusion-tritonserver#3]
Hi Kamal - I was wondering how you have converted the diffusion model to onnx. I have tried the official implementation from here but it doesn't seem to produce the right onnx file. 

https://github.com/huggingface/diffusers/blob/main/scripts/convert_stable_diffusion_checkpoint_to_onnx.py

Can you please let me know how you have done the conversion.

**Comment by kamalkraj** [comment]
Try [v2](https://github.com/kamalkraj/stable-diffusion-tritonserver/tree/v2) branch  - WIP

Please let me know if any issues
