### ISSUE TITLE
Great work, any donation possibilities?

### ISSUE THREAD

**Issue by Vozf** [kamalkraj/stable-diffusion-tritonserver#5]

**Comment by kamalkraj** [comment]
I am glad you found the project helpful. Currently not accepting any donations.

**Comment by kamalkraj** [comment]
Checkout branch [v3](https://github.com/kamalkraj/stable-diffusion-tritonserver/tree/v3) for getting maximum speed on v1-4 models

**Comment by Vozf** [comment]
Thanks, I will. Let me know if you change your mind about donations
